In [14]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
from preprocess import *
import tf_varify

In [ ]:
preprocess_run()

In [ ]:
tf_varify.tf_varify()

In [12]:
!python model_woody.py --num_epochs=200 


2019-04-18 13:52:43.583108: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-18 13:52:43.646712: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-18 13:52:43.647073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.21GiB
2019-04-18 13:52:43.647086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-04-18 13:52:43.818355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-18 13:52:43.818385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]    

Step 2400: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 17.24, training_acc = 0.71 (0.142 sec)
                             val_loss(test_loss) = 49.35, val_acc(test_acc) = 0.41
best shot model: test_loss = 49.35, step = 2400
model saved successfully.
Step 2500: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 48.84, training_acc = 0.93 (0.141 sec)
                             val_loss(test_loss) = 79.06, val_acc(test_acc) = 0.16
Step 2600: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 21.17, training_acc = 0.71 (0.141 sec)
                             val_loss(test_loss) = 51.53, val_acc(test_acc) = 0.37
Step 2700: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 19.48, training_acc = 0.50 (0.141 sec)
                             val_loss(test_loss) = 60.42,

Step 5800: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 11.72, training_acc = 0.17 (0.142 sec)
                             val_loss(test_loss) = 68.93, val_acc(test_acc) = 0.20
Step 5900: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 49.63, training_acc = 0.68 (0.142 sec)
                             val_loss(test_loss) = 47.91, val_acc(test_acc) = 0.43
Step 6000: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 15.06, training_acc = 0.76 (0.141 sec)
                             val_loss(test_loss) = 49.88, val_acc(test_acc) = 0.31
Step 6100: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 6.12, training_acc = 0.88 (0.143 sec)
                             val_loss(test_loss) = 47.46, val_acc(test_acc) = 0.38
Step 6200: (loss func: MSE, acc func: Pearson cor

Step 9300: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 24.67, training_acc = 0.99 (0.143 sec)
                             val_loss(test_loss) = 32.95, val_acc(test_acc) = 0.52
Step 9400: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 20.36, training_acc = 0.28 (0.141 sec)
                             val_loss(test_loss) = 49.02, val_acc(test_acc) = 0.39
Step 9500: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 36.08, training_acc = 0.86 (0.144 sec)
                             val_loss(test_loss) = 54.42, val_acc(test_acc) = 0.37
Step 9600: (loss func: MSE, acc func: Pearson correlation coefficient)
                             training_loss = 39.11, training_acc = 0.96 (0.142 sec)
                             val_loss(test_loss) = 31.36, val_acc(test_acc) = 0.67
Step 9700: (loss func: MSE, acc func: Pearson co

In [21]:
!python model_woody.py --num_epochs=200 --for_test=True

l1_conv3d/Relu   [None, 67, 67, 67, 16]
l1_conv3d/max_pool3d   [None, 34, 34, 34, 16]
l2_conv3d/Relu   [None, 34, 34, 34, 32]
l2_conv3d/max_pool3d   [None, 17, 17, 17, 32]
l3_conv3d/Relu   [None, 17, 17, 17, 64]
l3_conv3d/max_pool3d   [None, 9, 9, 9, 64]
l4_conv3d/Relu   [None, 9, 9, 9, 64]
l4_conv3d/max_pool3d   [None, 5, 5, 5, 64]
l5_conv3d/Relu   [None, 5, 5, 5, 64]
l5_conv3d/max_pool3d   [None, 3, 3, 3, 64]
l6_fc/fc_out1   [None, 512]
l6_fc/dropout1/mul   [None, 512]
l7_fc/fc_out2   [None, 128]
l7_fc/dropout2/mul   [None, 128]
l8_fc/final_output   [None, 1]
2019-04-18 15:13:09.497672: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-18 15:13:09.567190: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-18 15:13:09.567565: I tensorfl

In [ ]:
!python model_zach.py --num_epochs=200 

In [ ]:
DESIRED_SHAPE = (130,130,130)

nii = nib.load('/media/woody/Elements/age_data/ABIDE_I/anat_data/50002.nii.gz')
arr = nii.get_data()
header = nii.header
pixdim = np.round(header['pixdim'][1:4],4)
resampled_img = resample(arr, pixdim, [2,2,2])
crop_padded_img = crop_pad_abide(resampled_img,DESIRED_SHAPE)
crop_padded_img = np.round(crop_padded_img)

In [ ]:
print2d(arr)

In [ ]:
print2d(resampled_img)

In [ ]:
print2d(crop_padded_img)

In [ ]:
resampled_img_2 = resample(arr, pixdim, [4,4,4])
crop_padded_img_2 = crop_pad_abide(resampled_img_2,(65,65,65))
crop_padded_img_2 = np.round(crop_padded_img_2)

In [ ]:
print2d(resampled_img_2)
print2d(crop_padded_img_2)


In [ ]:
crop_padded_img_3 = crop_pad(resampled_img_2,(67,67,67))
crop_padded_img_3 = np.round(crop_padded_img_3)

In [ ]:
print2d(crop_padded_img_3)

In [ ]:
np.corrcoef(a)[0][1]

In [ ]:
a = np.array([[100,2,3],[3,40,100]])

In [7]:
ta = tf.constant([100,2,3])
tb = tf.constant([3,40,100])
tc = np.array([1,2,3])
with tf.Session() as sess:
    print(sess.run(tf.reshape(ta,[-1,1])-tf.reshape(ta,[-1,])))

[[  0  98  97]
 [-98   0  -1]
 [-97   1   0]]


In [10]:
np.sqrt(4)

2.0

In [ ]:
tf.contrib.metrics.streaming_pearson_correlation?

In [ ]:
np.vstack((np.array([1,2]),np.array([3,4])))

In [ ]:
np.corrcoef?

In [ ]:
arr_npy.dtype == decode_arr.dtype

In [ ]:
decode_arr.dtype

In [ ]:
np.sum(arr_npy - decode_arr)

In [ ]:
tf.reduce_mean?

In [ ]:
np.vstack([1,2],[3,4])